Description: AWS ElatiCache for Redis Mode Demonstration

Parameters:

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: security groups from applications side/ this can be refer directly from output
  
  ProjectName:
    Type: String
    Default: aws-elasticache

  CacheNodeType:
    Type: String
    Default: cache.t3.micro
  EngineVersion:
    Description: 'Redis version'
    Type: String
    Default: '5.0.6'
    AllowedValues: # aws elasticache describe-cache-engine-versions --engine redis --query "CacheEngineVersions[].EngineVersion"
    - '3.2.6' # 3.2.4 and 3.2.10 do not support encryption
    - '4.0.10'
    - '5.0.0'
    - '5.0.3'
    - '5.0.4'
    - '5.0.5'
    - '5.0.6'
    - '6.x'
  AutomaticFailoverEnabled: 
    Description: 'Enable Automatic failover'
    Type: 'String'
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'
  TransitEncryptionEnabled:
    Description: 'Enable encryption for data in transit  
 #(see https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/in-transit-encryption.html)'
    Type: 'String'
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'
  AuthToken:
    Description: 'Optional password (16 to 128 characters) used to authenticate against Redis (requires TransitEncryption := true; leave blank to disable password-protection).'
    Type: 'String'
    MaxLength: 128
    AllowedPattern: ^(?=.*\d)(?=.*[a-zA-Z]).{16,128}$
  NumShards:
    Description: 'Number of shards in the cluster.'
    Type: 'Number'
    Default: 1
    MinValue: 1
    MaxValue: 250
  NumReplicas:
    Description: 'Number of replicas per shard.'
    Type: 'Number'
    Default: 1
    MinValue: 0
    MaxValue: 5

Resources:
  RedisReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      AutoMinorVersionUpgrade: true
      AutomaticFailoverEnabled: !Ref AutomaticFailoverEnabled
      CacheParameterGroupName: default.redis5.0
      CacheNodeType: !Ref CacheNodeType
      CacheSubnetGroupName:  !Ref RedisSubnetGroup
      Engine: redis
      EngineVersion: !Ref EngineVersion
      Port: 6379
      TransitEncryptionEnabled: !Ref TransitEncryptionEnabled
      AuthToken: !Ref AuthToken
      NumNodeGroups: !Ref NumShards
      ReplicasPerNodeGroup: !Ref NumReplicas
      ReplicationGroupDescription: Sample Redis group for scaling
      SecurityGroupIds:
        - !Ref RedisSecurityGroup
      Tags:
        - Key: Project
          Value: !Ref ProjectName
  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Redis subnet group
      SubnetIds:
        - !ImportValue PrivateSubnet1
        - !ImportValue PrivateSubnet2
  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue VPC
      GroupDescription: Enable Redis access 
  SecurityGroupIngress:
    Type: "AWS::EC2::SecurityGroupIngress" 
    Properties:
      GroupId: !GetAtt [RedisSecurityGroup, GroupId]
      IpProtocol: tcp
      FromPort: 6379
      ToPort: 6379
      SourceSecurityGroupId: !Ref WebServerSecurityGroup
      Tags:
        - Key: Project
          Value: !Ref ProjectName
Outputs:
  URL:
    Description:  Newly created Elasticache Redis cluster Mode Demonstration
    Value: !Ref RedisReplicationGroup